version: '$VERSION_DOCKER_COMPOSE'
services:
  app:
    image:  $IMAGE_DOCKER
    restart: always
    build: 
      context: .
      dockerfile: Dockerfile
    networks:
      - app-network
  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf/nginx.conf
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    ports:
      - $CONTAINER_DOCKER_PORT:$NGINX_LISTEN_PORT
    networks:
      - app-network
networks:
  app-network:
    name: app-network
    driver: bridge
    external: true
  